baseURL: 'https://adiprasetyo.dev/'
defaultContentLanguage: en
hasCJKLanguage: false
defaultContentLanguageInSubdir: false
removePathAccents: true

build:
  writeStats: true
  enableGitInfo: false
  summaryLength: 30
  pagination:
    pagerSize: 10
  enableEmoji: true
  enableRobotsTXT: true
  ignoreFiles:
    - '\.ipynb$'
    - '.ipynb_checkpoints$'
    - '\.Rmd$'
    - '\.Rmarkdown$'
    - '_cache$'
  
permalinks:
  authors: '/author/:slug/'

outputs:
  home: [HTML, RSS]
  section: [HTML, RSS]

imaging:
  resampleFilter: lanczos
  quality: 80
  anchor: smart

timeout: 60000

taxonomies:
  author: authors
  tag: tags
  publication_type: publication_types

markup:
  highlight:
    lineNos: false

security:
  enableInlineScripts: false

sitemap:
  changefreq: daily
  priority: 0.5
  filename: sitemap.xml
  about:
  author: adi_prasetyo

